### PR TITLE
Added time parser using chrono library

### PR DESCRIPTION
**Pull request by mdhishaamakhtar**

### CODE REVIEW

**Review by YashKumarVerma — CHANGES_REQUESTED** [review]
add example usage as well

**Comment by mdhishaamakhtar** [comment]
Added comments with example

**Review by YashKumarVerma — CHANGES_REQUESTED** [review]
how to use this in main function, tell that

**Comment by mdhishaamakhtar** [comment]
Functions needed for these commands: 
- [ ] `:checkpoint revert`
- [ ] `:branch delete`
- [ ] `:branch accept`
- [ ] `:cloud attach`
- [ ] `:logs clean`

**Pull request merged**
